name: sample
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.3.9+31
version: 1.4.0+32

environment:
  #sdk: ">=2.0.0 <3.0.0"

  #Null Safety sdk
  sdk: ">=2.12.0 <3.0.0"
  # sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  introduction_screen: ^3.0.1
  # flutter_launcher_icons: ^0.7.0
  flutter_launcher_icons: ^0.10.0
  shared_preferences: ^2.0.15
  # change_app_package_name: ^0.1.2
  # curved_navigation_bar: ^0.3.2
  # google_fonts: ^1.1.0
  fl_toast: ^3.1.0
  tinycolor: ^1.0.2
  http: ^0.13.5
  date_field: ^2.1.3
  time_pickerr: ^1.0.6
  device_info_plus: ^3.2.0
  camera: ^0.9.2   
  image_picker: ^0.8.4
  screenshot: ^1.3.0
  geocoding: ^2.0.5
  location: ^4.4.0
  signature: ^4.1.1
  argon_buttons_flutter: ^1.1.0
  in_app_update: ^3.0.0
  path_provider: ^2.0.2
  plugin_platform_interface: ^2.0.1
  path_provider_platform_interface: ^2.0.0
  # url_launcher: ^6.1.5
  syncfusion_flutter_charts: ^19.1.54
  flutter_screenutil: ^5.5.2
  firebase_messaging: ^11.2.7
  firebase_core: ^1.12.0
  # firebase_core: ^1.13.1
  android_path_provider: ^0.3.0
  flutter_downloader: ^1.7.4
  permission_handler: ^9.0.2
  zoom_pinch_overlay: ^1.2.0
  sqflite: ^2.0.2
  table_calendar: ^3.0.0
  intl: ^0.17.0
  # webview_flutter: ^2.0.13
  webview_flutter: ^3.0.0
  lottie: ^1.2.2
  flutter_html: ^3.0.0-alpha.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  camera_android:
    git:
      url: https://github.com/elmar001/plugins.git
      path: packages/camera/camera_android
      ref: 5172b44088a4082ff0899594614c5380457d341b


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/launcher/
    - assets/images/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Segoe ui
      fonts: 
        - asset: assets/fonts/segoeui.ttf
        - asset: assets/fonts/seguibl.ttf
          weight: 700
        - asset: assets/fonts/segoeuib.ttf
        - asset: assets/fonts/seguili.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
          
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ikonci.png"
  image_path_android: "assets/launcher/newicon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"